### ISSUE TITLE
Feat: command to activate joinsounds in all channels

### ISSUE THREAD

**Issue by maybeanerd** [T0TProduction/MagiBot#114]
- should activate JS in all channels of a guild
- should probably also be able to deactivate JS for all channels
- I don't want to hardcode all channel IDs into the DB, this needs to be some sort of syntax that tells the bot that all channels are allowed, even if they are added to the guild after this command was used

**Comment by T0TProduction** [comment]
this is implemented with removing all voicechannels from the allow list - by default , all channels are allowed
